# Generated by Django 4.2.6 on 2023-10-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_course_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='course',
            name='schedule',
            field=models.CharField(max_length=11, verbose_name='Horario (HH:MM-HH:MM)'),
        ),
    ]
